### PR TITLE
Added OlegBash599/ZCTS_BROWSER

### PR DESCRIPTION
**Pull request by OlegBash599**
Is it possible to add WebDynpro development for transport of copies?
https://github.com/OlegBash599/ZCTS_BROWSER

The development is to be for transporting changes and testing.

### CODE REVIEW

**Comment by larshp** [comment]
Hi,
The `.abapgit.xml` file is missing in the root, please also add a license https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by OlegBash599** [comment]
> Hi,
> The `.abapgit.xml` file is missing in the root of https://github.com/OlegBash599/ZCTS_BROWSER, please also add a license https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

Hi,
1) abapgit.xml - added.
2) licence - added.
3) fork branch updated

**Comment by larshp** [comment]
welcome to dotabap.org 🎉 

the site will update automatically in a bit

**Comment by OlegBash599** [comment]
> welcome to dotabap.org 🎉
> 
> the site will update automatically in a bit

Thank you very much!

**Pull request merged**
