### PR TITLE
OlegBash599/ZC8A_00 : ABAP Similarity search with HANA and Oracle

### PR DESCRIPTION
**Pull request by OlegBash599**
OlegBash599/ZC8A_00 : ABAP Similarity search with HANA and Oracle

### CODE REVIEW

**Comment by larshp** [comment]
conflicts

also please dont sort the list, it makes it difficult to review

**Comment by OlegBash599** [comment]
For now I have added the line into the end of the list.

**Comment by larshp** [comment]
nice

the `.abapgit.xml` file is missing in the repository

**Comment by OlegBash599** [comment]
added

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
