### PR TITLE
add ztoad as project

### PR DESCRIPTION
**Pull request by marianfoo**

### CODE REVIEW

**Comment by larshp** [comment]
please make sure to add a license in the repo, https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by marianfoo** [comment]
@larshp  has been added

**Comment by larshp** [comment]
thanks 👍

**Comment by marianfoo** [comment]
@larshp thanks for adding

**Comment by larshp** [comment]
it will show up automatically on the page, but might be up to 24 hours

**Comment by marianfoo** [comment]
@larshp ah ok, thanks for the information

**Pull request merged**
