### PR TITLE
NamespaceChanger added.

### PR DESCRIPTION
**Pull request by mkysoft**
This project rename package, object and text in serialized abapGit code and download as zip file.

### CODE REVIEW

**Comment by larshp** [comment]
please add a license file for the project, see https://help.github.com/en/articles/adding-a-license-to-a-repository

**Comment by mkysoft** [comment]
> please add a license file for the project, see https://help.github.com/en/articles/adding-a-license-to-a-repository

I added LICENSE file, thanks for your attention.

**Comment by larshp** [comment]
I'm currently having some trouble building the list, see https://travis-ci.org/dotabap/dotabap-list, so your project will not show up right away

**Comment by larshp** [comment]
working again,
image

**Pull request merged**
