### PR TITLE
added abeljohny/ZAP

### PR DESCRIPTION
**Pull request by abeljohny**

### CODE REVIEW

**Comment by larshp** [comment]
hi, suggest converting to abapGit format, then the project can be added, see requirements https://github.com/dotabap/dotabap-list#dotabap-list

**Review by larshp — CHANGES_REQUESTED** [review]
see above

**Comment by abeljohny** [comment]
hey Lars, requested change is done.

**Review by abeljohny — COMMENTED** [review]
updated abeljohny/ZAP to abapGit format

**Comment by larshp** [comment]
it also needs the XML files for the PROGs

suggest copy pasting the ABAP into a system and then push it to github, https://docs.abapgit.org/user-guide/projects/online/moving-package.html#new-repository

**Comment by abeljohny** [comment]
the requested change's done Lars. Thank you!

**Review by larshp — APPROVED** [review]

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
